# Site settings
title: Mars's Blog
owner: Mars Shen
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://Mars-Shen.github.io"
twitter_username: Mars1Shen
github_username:  Mars-Shen
facebook_username:  marscatz
weibo_username:  catz123

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
