# Site settings
title: Mars's Blog
owner: Mars Shen
header-img: img/home-bg.jpg
email: 
description: "Mars的个人blog"
baseurl: ""
url: "http://www.marsshen.com/"
twitter_username: Mars1Shen
github_username:  Mars-Shen
facebook_username:  marscatz
weibo_username:  catz123

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate,jekyll-gist]
